# Generated by Django 3.0.4 on 2020-03-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DRFUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('kenya', 0), ('uganda', 1), ('tanzania', 2)], default='kenya', max_length=50)),
            ],
            options={
                'ordering': ['firstName'],
            },
        ),
    ]
